# Generated by Django 4.2.7 on 2023-11-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nation', models.CharField(max_length=100)),
                ('unit', models.TextField(max_length=100)),
                ('price', models.TextField()),
            ],
        ),
    ]
