# Generated by Django 4.2.7 on 2023-11-23 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('fin_prdt_cd', models.TextField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=300)),
                ('deposit_name', models.TextField()),
                ('join_way', models.TextField()),
                ('join_member', models.TextField()),
                ('option6', models.TextField(default='-')),
                ('option12', models.TextField(default='-')),
                ('option24', models.TextField(default='-')),
                ('option36', models.TextField(default='-')),
                ('maxoption6', models.TextField(default='-')),
                ('maxoption12', models.TextField(default='-')),
                ('maxoption24', models.TextField(default='-')),
                ('maxoption36', models.TextField(default='-')),
            ],
        ),
        migrations.CreateModel(
            name='RentalLoan',
            fields=[
                ('fin_prdt_cd', models.TextField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=300)),
                ('deposit_name', models.TextField()),
                ('erly_rpay_fee', models.TextField()),
                ('dly_rate', models.TextField()),
                ('loan_lmt', models.TextField()),
                ('join_way', models.TextField()),
                ('loan_inci_expn', models.TextField()),
                ('dcls_strt_day', models.TextField()),
                ('dcls_end_day', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('fin_prdt_cd', models.TextField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=300)),
                ('deposit_name', models.TextField()),
                ('join_way', models.TextField()),
                ('join_member', models.TextField()),
                ('option6', models.TextField(default='-')),
                ('option12', models.TextField(default='-')),
                ('option24', models.TextField(default='-')),
                ('option36', models.TextField(default='-')),
                ('maxoption6', models.TextField(default='-')),
                ('maxoption12', models.TextField(default='-')),
                ('maxoption24', models.TextField(default='-')),
                ('maxoption36', models.TextField(default='-')),
            ],
        ),
        migrations.CreateModel(
            name='RentalLoanOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField()),
                ('rpay_type_nm', models.TextField()),
                ('lend_rate_type_nm', models.TextField()),
                ('lend_rate_min', models.FloatField()),
                ('lend_rate_max', models.FloatField()),
                ('rentalloan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='bankings.rentalloan')),
            ],
        ),
    ]
